extends SceneTree
const MIX := preload("res://scripts/audio/movement_audio_mix.gd")
const EVENTS := preload("res://scripts/audio/sound_event_catalog.gd")
const VOICE := preload("res://scripts/audio/sound_event_voice.gd")
const TEST_ROOT := "res://build/sound_event_tuning_test"

func _init() -> void:
	call_deferred("_run")
	create_timer(35.0).timeout.connect(func() -> void: quit(1))

func _run() -> void:
	var original_hash := FileAccess.get_sha256(MIX.SAVE_PATH)
	MIX.initialize()
	var existing_grass := MIX.copy_banks(MIX.saved)
	assert(not MIX.has_changes(), "Loading an older mix must not create unsaved edits.")
	# Split older shared forest choices without sharing mutable settings, and
	# never repopulate an explicitly empty Level 2 bank in a newer mix.
	var old_forest: Resource = EVENTS.default_banks()["ambience/forest"]
	old_forest.clips.append(AudioStreamWAV.new())
	old_forest.labels.append("Existing forest")
	old_forest.volume_db = -27.0
	old_forest.selection_mode = 1
	old_forest.fixed_index = 0
	var migrated := MIX.copy_saved_events({"ambience/forest": old_forest})
	assert(migrated["ambience/level_2_forest"].volume_db == -27.0)
	assert(migrated["ambience/level_2_forest"].fixed_index == 0)
	migrated["ambience/level_2_forest"].clips.clear()
	migrated["ambience/level_2_forest"].volume_db = -40.0
	assert(migrated["ambience/forest"].clips.size() == 1 and old_forest.clips.size() == 1)
	assert(migrated["ambience/forest"].volume_db == -27.0)
	var reloaded := MIX.copy_saved_events(migrated)
	assert(reloaded["ambience/level_2_forest"].clips.is_empty())
	assert(reloaded["ambience/level_2_forest"].volume_db == -40.0)
	var old_player_cue: Resource = EVENTS.default_banks()["combat/player_death"]
	old_player_cue.clips.append(AudioStreamWAV.new())
	old_player_cue.volume_db = -21.0
	var player_cues := MIX.copy_saved_events({"combat/player_death": old_player_cue})
	assert(player_cues["combat/player_hit"].clips.size() == 1)
	assert(player_cues["combat/player_hit"].volume_db == -21.0)
	player_cues["combat/player_hit"].clips.clear()
	player_cues["combat/player_hit"].volume_db = -35.0
	assert(player_cues["combat/player_death"].clips.size() == 1 and old_player_cue.clips.size() == 1)
	assert(player_cues["combat/player_death"].volume_db == -21.0)
	var reloaded_cues := MIX.copy_saved_events(player_cues)
	assert(reloaded_cues["combat/player_hit"].clips.is_empty())
	assert(reloaded_cues["combat/player_hit"].volume_db == -35.0)
	# User-saved event choices must not turn this fixture test into a failure
	# later. Reset only its in-memory event banks, preserving actual surfaces.
	MIX.saved_events = EVENTS.default_banks()
	MIX.working_events = MIX.copy_banks(MIX.saved_events)
	# Empty defaults are generated by the catalog, never by selecting sounds.
	var seen := {}
	for entry in EVENTS.EVENTS:
		assert(not seen.has(entry.id), "Sound event identifiers must be unique.")
		seen[entry.id] = true
		assert(EVENTS.CATEGORIES.has(str(entry.id).get_slice("/", 0)))
		if not entry.has("room"):
			assert(MIX.event_bank_for(entry.id) != null)
			assert(MIX.event_bank_for(entry.id).clips.is_empty())
	var random := RandomNumberGenerator.new()
	var bank := MIX.event_bank_for("combat/player_gunshot")
	assert(bank.choose_clip(random) == -1)
	# Generated test audio stays in build; production slots remain empty.
	DirAccess.make_dir_recursive_absolute(TEST_ROOT)
	var fixture := AudioStreamWAV.new()
	fixture.format = AudioStreamWAV.FORMAT_16_BITS
	fixture.mix_rate = 22050
	var pcm := PackedByteArray()
	pcm.resize(2205 * 2)
	for sample_index in 2205:
		pcm.encode_s16(sample_index * 2, roundi(600 * sin(sample_index * TAU * 440.0 / 22050.0)))
	fixture.data = pcm
	assert(fixture.save_to_wav(TEST_ROOT + "/fixture.wav") == OK)
	var external := MIX.load_recording(TEST_ROOT + "/fixture.wav")
	bank.clips.append(external)
	bank.clips.append(external)
	bank.labels = PackedStringArray(["Test A", "Test B"])
	bank.volume_db = -28.0
	bank.pitch_scale = 1.2
	bank.pitch_variation = 0.07
	bank.repeat_interval = 0.4
	bank.use_room_reverb = false
	bank.selection_mode = 1
	bank.fixed_index = 1
	assert(bank.choose_clip(random, 1) == 1)
	bank.disabled_indices = PackedInt32Array([1])
	assert(bank.choose_clip(random) == -1, "A disabled fixed recording must remain silent.")
	bank.disabled_indices.clear()
	bank.selection_mode = 0
	for attempt in 16:
		assert(bank.choose_clip(random, 0) == 1)
		assert(bank.choose_clip(random, 1) == 0)
		var pitch: float = bank.choose_pitch(random)
		assert(pitch >= 1.13 and pitch <= 1.27)
	bank.enabled = false
	assert(bank.choose_clip(random) == -1)
	bank.enabled = true
	assert(MIX.saved_events["combat/player_gunshot"].clips.is_empty())
	assert(MIX.has_changes())
	MIX.listening_to_saved = true
	assert(MIX.event_bank_for("combat/player_gunshot").clips.is_empty())
	MIX.listening_to_saved = false
	var loop := MIX.event_bank_for("world/lift_motor")
	loop.clips.append(external)
	loop.labels.append("Test loop")
	assert(MIX.save_defaults(TEST_ROOT + "/mix.tres", TEST_ROOT + "/recordings") == OK)
	assert(not MIX.has_changes())
	var loaded := ResourceLoader.load(TEST_ROOT + "/mix.tres", "", ResourceLoader.CACHE_MODE_IGNORE)
	var restored: Resource = loaded.event_banks["combat/player_gunshot"]
	assert(restored.pitch_scale == 1.2 and restored.pitch_variation == 0.07)
	assert(restored.repeat_interval == 0.4 and not restored.use_room_reverb)
	assert(restored.clips[0].resource_path.begins_with(TEST_ROOT + "/recordings"))
	assert(restored.clips[0].has_meta("source_sha256"))
	assert(loaded.event_banks["world/lift_motor"].looping)
	assert(loaded.banks["grass/run"].volume_db == existing_grass["grass/run"].volume_db)
	MIX.event_bank_for("combat/player_gunshot").enabled = false
	assert(MIX.save_defaults(TEST_ROOT + "/mix.tres", TEST_ROOT + "/recordings") == OK)
	loaded = ResourceLoader.load(TEST_ROOT + "/mix.tres", "", ResourceLoader.CACHE_MODE_IGNORE)
	assert(not loaded.event_banks["combat/player_gunshot"].enabled)
	MIX.event_bank_for("combat/player_gunshot").volume_db = -25.0
	assert(MIX.save_defaults(TEST_ROOT + "/missing/mix.tres") != OK)
	assert(MIX.saved_events["combat/player_gunshot"].volume_db == -28.0)
	MIX.revert()
	assert(not MIX.has_changes())

	var game: Node = load("res://scenes/app/game_root.tscn").instantiate()
	game.persist_progression = false
	root.add_child(game)
	await process_frame
	game.load_level(&"arrival_shoreline")
	for frame in 8:
		await physics_frame
	var panel: CanvasLayer = game.audio_tuning_panel
	panel.open_panel()
	assert(paused)
	# Every registered entry can be selected, including the existing room beds.
	for category in EVENTS.CATEGORIES:
		panel._select_category(category)
		assert(panel.category == category)
	for entry in EVENTS.EVENTS:
		panel.select_event(entry.id)
		assert(panel.event_id == entry.id)
		assert(panel._kind_picker.get_item_metadata(panel._kind_picker.selected) == entry.id)
	panel.select_event("abilities/double_jump")
	panel._preview_contact()
	assert(not panel._event_voice.playing)
	panel._add_files(PackedStringArray([TEST_ROOT + "/fixture.wav", TEST_ROOT + "/fixture.wav"]))
	bank = MIX.event_bank_for("abilities/double_jump")
	assert(bank.clips.size() == 2)
	var selection: OptionButton = panel._body.find_child("EventSelection", true, false)
	selection.item_selected.emit(1)
	var fixed: OptionButton = panel._body.find_child("EventFixedRecording", true, false)
	fixed.item_selected.emit(2)
	assert(bank.selection_mode == 1 and bank.fixed_index == 1)
	panel._remove_clip(0)
	assert(bank.fixed_index == 0)
	var pitch_control: SpinBox = panel._body.find_child("EventPitchScale", true, false)
	pitch_control.value = 1.1
	assert(bank.pitch_scale == 1.1)
	panel._toggle_comparison()
	assert(not (panel._body.find_child("EventPitchScale", true, false) as SpinBox).editable)
	panel._add_files(PackedStringArray([TEST_ROOT + "/fixture.wav"]))
	assert(MIX.saved_events["abilities/double_jump"].clips.is_empty(), "A must stay read-only.")
	panel._toggle_comparison()
	assert(MIX.event_bank_for("abilities/double_jump").clips.size() == 1)
	panel._preview_contact()
	assert(panel._event_voice.playing)
	assert(is_equal_approx(panel._event_voice.pitch_scale, 1.1))
	panel._remove_clip(0)
	assert(bank.fixed_index == -1 and not panel._event_voice.playing)

	panel.select_event("world/lift_motor")
	panel._space.item_selected.emit(1)
	panel._preview_contact()
	assert(panel._event_voice.playing and panel._event_voice.stream.loop_mode == AudioStreamWAV.LOOP_FORWARD)
	assert(panel._event_voice.bus == MIX.PREVIEW_BUS)
	assert(MIX.event_bank_for("world/lift_motor").clips[0].loop_mode == AudioStreamWAV.LOOP_DISABLED)
	MIX.event_bank_for("world/lift_motor").repeat_interval = 0.1
	var looping_stream: AudioStream = panel._event_voice.stream
	panel._repeat_button.pressed.emit()
	await create_timer(0.35).timeout
	assert(panel._event_voice.playing, "A loop must survive multiple source lengths while paused.")
	assert(panel._event_voice.stream == looping_stream, "Repeat must not restart a playing loop.")
	panel._stop_button.pressed.emit()
	assert(not panel._event_voice.playing and not panel._repeat)
	var room_toggle: CheckBox = panel._body.find_child("EventRoomReverb", true, false)
	room_toggle.button_pressed = false
	panel._preview_contact()
	assert(panel._event_voice.bus == &"Master")
	var playback: OptionButton = panel._body.find_child("EventPlayback", true, false)
	playback.item_selected.emit(0)
	assert(not panel._event_voice.playing)
	panel._preview_contact()
	await create_timer(0.3).timeout
	assert(not panel._event_voice.playing, "Play once must stop at the end.")
	MIX.event_bank_for("world/lift_motor").pitch_scale = 0.5
	panel._repeat_button.pressed.emit()
	panel._process(0.01)
	var first_one_shot: AudioStream = panel._event_voice.stream
	await create_timer(0.11).timeout
	assert(panel._event_voice.stream == first_one_shot, "Repeat must allow a long one-shot to finish.")
	await create_timer(0.35).timeout
	assert(panel._event_voice.stream != first_one_shot, "Repeat must play another one-shot after it finishes.")
	panel._stop_button.pressed.emit()
	for source_path in ["res://assets/audio/footsteps/sand_dirt_004.ogg", "res://assets/audio/water/heavy-water-splash.mp3"]:
		var source := MIX.load_recording(source_path)
		var original_loop: bool = source.loop
		assert(VOICE.playback_copy(source, true).loop)
		assert(not VOICE.playback_copy(source, false).loop)
		assert(source.loop == original_loop)
	panel.select_event("world/lift_motor")
	MIX.event_bank_for("world/lift_motor").looping = true
	panel._preview_contact()
	panel._toggle_comparison()
	assert(not panel._event_voice.playing, "A/B must stop the previous voice.")
	panel._toggle_comparison()
	panel._preview_contact()
	panel._select_category("movement")
	assert(not panel._event_voice.playing)
	assert(panel._surface_picker.visible and panel._pace.visible)
	panel.select_event("ambience/cave")
	assert(panel._is_room_ambience() and panel.listening_environment() == &"cave")
	assert(panel._body.find_child("CaveAmbienceEnabled", true, false) != null)
	panel.select_event("world/lift_motor")
	panel._preview_contact()
	panel.close_panel()
	assert(not paused and not panel._event_voice.playing)
	# Closing a panel opened over an already paused game preserves that pause.
	paused = true
	panel.open_panel()
	panel.close_panel()
	assert(paused)
	paused = false
	# Connections exist even for empty banks; adding a recording is sufficient.
	var player: PlayerCharacter = game.current_level.player
	assert(not player.ability_performed.get_connections().is_empty())
	assert(game.current_level.has_node("EventAudio"))
	MIX.revert()
	game.free()
	assert(FileAccess.get_sha256(MIX.SAVE_PATH) == original_hash, "Validation must preserve the user's mix byte-for-byte.")
	print("Sound event tuning passed: empty catalog, legacy mix, selection, A/B, persistence, promotion, controls, loops, routing, gameplay connections and cleanup.")
	quit()
